var webpack=require('webpack');
module.exports={
    entry:{
        RecommendListBundle:__dirname+"/src/recommend-newsList.js",
        ScienceListBundle:__dirname+"/src/science-newsList.js",
        NBAListBundle:__dirname+"/src/nba-newsList.js",
        RecommendDetailBundle1:__dirname+"/src/recommend-newsDetail-1.js",
        RecommendDetailBundle2:__dirname+"/src/recommend-newsDetail-2.js",
        RecommendDetailBundle3:__dirname+"/src/recommend-newsDetail-3.js",
        RecommendDetailBundle4:__dirname+"/src/recommend-newsDetail-4.js",
        RecommendDetailBundle5:__dirname+"/src/recommend-newsDetail-5.js",
        RecommendDetailBundle6:__dirname+"/src/recommend-newsDetail-6.js",
        RecommendDetailBundle7:__dirname+"/src/recommend-newsDetail-7.js",
        RecommendDetailBundle8:__dirname+"/src/recommend-newsDetail-8.js",
        RecommendDetailBundle9:__dirname+"/src/recommend-newsDetail-9.js",
        RecommendCommentBudle1:__dirname+"/src/recommend-newsComment-1.js",
        RecommendCommentBudle2:__dirname+"/src/recommend-newsComment-2.js",
        RecommendCommentBudle3:__dirname+"/src/recommend-newsComment-3.js",
        RecommendCommentBudle4:__dirname+"/src/recommend-newsComment-4.js",
        RecommendCommentBudle5:__dirname+"/src/recommend-newsComment-5.js",
        RecommendCommentBudle6:__dirname+"/src/recommend-newsComment-6.js",
        RecommendCommentBudle7:__dirname+"/src/recommend-newsComment-7.js",
        RecommendCommentBudle8:__dirname+"/src/recommend-newsComment-8.js",
        RecommendCommentBudle9:__dirname+"/src/recommend-newsComment-9.js",
        ScienceDetailBundle1:__dirname+"/src/science-newsDetail-1.js",
        ScienceDetailBundle2:__dirname+"/src/science-newsDetail-2.js",
        ScienceDetailBundle3:__dirname+"/src/science-newsDetail-3.js",
        ScienceDetailBundle4:__dirname+"/src/science-newsDetail-4.js",
        ScienceDetailBundle5:__dirname+"/src/science-newsDetail-5.js",
        ScienceDetailBundle6:__dirname+"/src/science-newsDetail-6.js",
        ScienceDetailBundle7:__dirname+"/src/science-newsDetail-7.js",
        ScienceDetailBundle8:__dirname+"/src/science-newsDetail-8.js",
        ScienceDetailBundle9:__dirname+"/src/science-newsDetail-9.js",
        ScienceCommentBudle1:__dirname+"/src/science-newsComment-1.js",
        ScienceCommentBudle2:__dirname+"/src/science-newsComment-2.js",
        ScienceCommentBudle3:__dirname+"/src/science-newsComment-3.js",
        ScienceCommentBudle4:__dirname+"/src/science-newsComment-4.js",
        ScienceCommentBudle5:__dirname+"/src/science-newsComment-5.js",
        ScienceCommentBudle6:__dirname+"/src/science-newsComment-6.js",
        ScienceCommentBudle7:__dirname+"/src/science-newsComment-7.js",
        ScienceCommentBudle8:__dirname+"/src/science-newsComment-8.js",
        ScienceCommentBudle9:__dirname+"/src/science-newsComment-9.js",
        NBADetailBundle1:__dirname+"/src/nba-newsDetail-1.js",
        NBADetailBundle2:__dirname+"/src/nba-newsDetail-2.js",
        NBADetailBundle3:__dirname+"/src/nba-newsDetail-3.js",
        NBADetailBundle4:__dirname+"/src/nba-newsDetail-4.js",
        NBADetailBundle5:__dirname+"/src/nba-newsDetail-5.js",
        NBADetailBundle6:__dirname+"/src/nba-newsDetail-6.js",
        NBADetailBundle7:__dirname+"/src/nba-newsDetail-7.js",
        NBADetailBundle8:__dirname+"/src/nba-newsDetail-8.js",
        NBADetailBundle9:__dirname+"/src/nba-newsDetail-9.js",
        NBACommentBudle1:__dirname+"/src/nba-newsComment-1.js",
        NBACommentBudle2:__dirname+"/src/nba-newsComment-2.js",
        NBACommentBudle3:__dirname+"/src/nba-newsComment-3.js",
        NBACommentBudle4:__dirname+"/src/nba-newsComment-4.js",
        NBACommentBudle5:__dirname+"/src/nba-newsComment-5.js",
        NBACommentBudle6:__dirname+"/src/nba-newsComment-6.js",
        NBACommentBudle7:__dirname+"/src/nba-newsComment-7.js",
        NBACommentBudle8:__dirname+"/src/nba-newsComment-8.js",
        NBACommentBudle9:__dirname+"/src/nba-newsComment-9.js",
    },
    output:{
        path:__dirname+"/build",
        filename:"[name].js"
    },
    resolve:{
        extensions:['.js','.jsx'],
    },
    module:{
        loaders:[
            {test:/\.js$/,loader:"babel-loader",exclude:/node_modules/},
            {test:/\.css$/,loader:"style-loader!css-loader"},
            {test:/\.less$/,loader:"style-loader!css-loader!less-loader"}
        ]
    },
    plugins:[
        new webpack.ProvidePlugin({
            $:"jquery",
            jQuery:"jquery",
            "window.jQuery":"jquery"
        })
    ]
}
